/* ==========================================================================
   LANDGUARD AI - Mock Dataset (Complete 48 Projects)
   Dakshina Kannada District, Karnataka | Capstone Demo Data
   ========================================================================== */

const LANDGUARD_MOCK_DATA = {
  // District Overview Metrics
  summary: {
    totalProjects: 48,
    highRiskCount: 12,
    medRiskCount: 21,
    lowRiskCount: 15,
    avgDelayProbability: 57.4,
    pendingCompensationCr: 18.6,
    activeLegalDisputes: 23,
    lastUpdated: "29 Sep 2026, 10:42 PM",
    aiModel: "Random Forest Classifier (v2.4 Prototype)",
    accuracyConfidence: "89.2%"
  },

  // Taluk Statistics (Sums to 48 projects, 12 High Risk)
  taluks: [
    { name: "Mangaluru", projects: 14, highRisk: 4, avgDelayProb: 62.1, compensationPaidPct: 58, legalDisputes: 8 },
    { name: "Bantwal", projects: 8, highRisk: 2, avgDelayProb: 54.3, compensationPaidPct: 72, legalDisputes: 4 },
    { name: "Belthangady", projects: 6, highRisk: 1, avgDelayProb: 48.0, compensationPaidPct: 81, legalDisputes: 2 },
    { name: "Puttur", projects: 7, highRisk: 2, avgDelayProb: 59.8, compensationPaidPct: 65, legalDisputes: 4 },
    { name: "Sullia", projects: 4, highRisk: 1, avgDelayProb: 51.2, compensationPaidPct: 79, legalDisputes: 1 },
    { name: "Kadaba", projects: 4, highRisk: 1, avgDelayProb: 53.7, compensationPaidPct: 74, legalDisputes: 2 },
    { name: "Moodbidri", projects: 5, highRisk: 1, avgDelayProb: 49.5, compensationPaidPct: 84, legalDisputes: 2 }
  ],

  // 48 Monitored Projects across Dakshina Kannada District
  projects: [
    // --- MANGALURU TALUK (14 Projects: 4 High, 6 Med, 4 Low) ---
    {
      id: "DK-LA-001",
      name: "Mangaluru Coastal Infrastructure Expansion",
      taluk: "Mangaluru",
      village: "Panambur",
      projectType: "Port & Logistics Corridor",
      landAreaAcres: 42.5,
      affectedFamilies: 86,
      compensationProgressPct: 48,
      rehabilitationProgressPct: 32,
      documentationProgressPct: 68,
      legalDisputes: 7,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 36,
      delayProbabilityPct: 82,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.9450,
      longitude: 74.8150
    },
    {
      id: "DK-LA-008",
      name: "Mangaluru Smart Logistics Hub",
      taluk: "Mangaluru",
      village: "Baikampady",
      projectType: "Logistics Hub",
      landAreaAcres: 65.0,
      affectedFamilies: 110,
      compensationProgressPct: 41,
      rehabilitationProgressPct: 28,
      documentationProgressPct: 50,
      legalDisputes: 11,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 48,
      delayProbabilityPct: 89,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.9610,
      longitude: 74.8290
    },
    {
      id: "DK-LA-011",
      name: "Surathkal IT & Hardware Park",
      taluk: "Mangaluru",
      village: "Surathkal",
      projectType: "Technology Park",
      landAreaAcres: 32.0,
      affectedFamilies: 54,
      compensationProgressPct: 45,
      rehabilitationProgressPct: 35,
      documentationProgressPct: 55,
      legalDisputes: 6,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 30,
      delayProbabilityPct: 76,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.9820,
      longitude: 74.8020
    },
    {
      id: "DK-LA-012",
      name: "Jeppu Riverfront Promenade & Road",
      taluk: "Mangaluru",
      village: "Jeppu",
      projectType: "Urban Road Corridor",
      landAreaAcres: 18.5,
      affectedFamilies: 62,
      compensationProgressPct: 42,
      rehabilitationProgressPct: 30,
      documentationProgressPct: 60,
      legalDisputes: 5,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 74,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.8550,
      longitude: 74.8420
    },
    {
      id: "DK-LA-013",
      name: "Urwa Sub-Station Grid Power Expansion",
      taluk: "Mangaluru",
      village: "Urwa",
      projectType: "Power Substation",
      landAreaAcres: 8.2,
      affectedFamilies: 12,
      compensationProgressPct: 65,
      rehabilitationProgressPct: 55,
      documentationProgressPct: 72,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 52,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8820,
      longitude: 74.8310
    },
    {
      id: "DK-LA-014",
      name: "Kulshekar Ring Road Feeder",
      taluk: "Mangaluru",
      village: "Kulshekar",
      projectType: "Ring Road Expansion",
      landAreaAcres: 14.0,
      affectedFamilies: 28,
      compensationProgressPct: 68,
      rehabilitationProgressPct: 58,
      documentationProgressPct: 75,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 20,
      delayProbabilityPct: 48,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8910,
      longitude: 74.8710
    },
    {
      id: "DK-LA-015",
      name: "Bajpe Airport Cargo Corridor",
      taluk: "Mangaluru",
      village: "Bajpe",
      projectType: "Airport Cargo Link",
      landAreaAcres: 24.5,
      affectedFamilies: 38,
      compensationProgressPct: 60,
      rehabilitationProgressPct: 50,
      documentationProgressPct: 68,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 24,
      delayProbabilityPct: 58,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.9580,
      longitude: 74.8890
    },
    {
      id: "DK-LA-016",
      name: "Ullal Coastal Protection & Bridge",
      taluk: "Mangaluru",
      village: "Ullal",
      projectType: "Coastal Protection",
      landAreaAcres: 16.0,
      affectedFamilies: 45,
      compensationProgressPct: 58,
      rehabilitationProgressPct: 48,
      documentationProgressPct: 65,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 24,
      delayProbabilityPct: 61,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8050,
      longitude: 74.8510
    },
    {
      id: "DK-LA-017",
      name: "Bondel Civic Administration Layout",
      taluk: "Mangaluru",
      village: "Bondel",
      projectType: "Administrative Complex",
      landAreaAcres: 11.2,
      affectedFamilies: 15,
      compensationProgressPct: 72,
      rehabilitationProgressPct: 62,
      documentationProgressPct: 80,
      legalDisputes: 1,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 44,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.9100,
      longitude: 74.8620
    },
    {
      id: "DK-LA-018",
      name: "Gurupura River Bridge Bypass",
      taluk: "Mangaluru",
      village: "Gurupura",
      projectType: "Bridge & Highway",
      landAreaAcres: 19.8,
      affectedFamilies: 26,
      compensationProgressPct: 64,
      rehabilitationProgressPct: 54,
      documentationProgressPct: 70,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 22,
      delayProbabilityPct: 50,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.9350,
      longitude: 74.9310
    },
    {
      id: "DK-LA-019",
      name: "Kenjar Industrial Sub-Zone",
      taluk: "Mangaluru",
      village: "Kenjar",
      projectType: "Industrial Estate",
      landAreaAcres: 28.0,
      affectedFamilies: 18,
      compensationProgressPct: 88,
      rehabilitationProgressPct: 82,
      documentationProgressPct: 92,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 18,
      delayProbabilityPct: 18,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.9480,
      longitude: 74.8780
    },
    {
      id: "DK-LA-020",
      name: "Adyar Renewable Energy Substation",
      taluk: "Mangaluru",
      village: "Adyar",
      projectType: "Power Substation",
      landAreaAcres: 9.5,
      affectedFamilies: 8,
      compensationProgressPct: 90,
      rehabilitationProgressPct: 85,
      documentationProgressPct: 94,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 15,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.8710,
      longitude: 74.9120
    },
    {
      id: "DK-LA-021",
      name: "Haleyangadi Logistics Rail Yard",
      taluk: "Mangaluru",
      village: "Haleyangadi",
      projectType: "Rail Logistics",
      landAreaAcres: 22.0,
      affectedFamilies: 16,
      compensationProgressPct: 85,
      rehabilitationProgressPct: 78,
      documentationProgressPct: 88,
      legalDisputes: 1,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 18,
      delayProbabilityPct: 24,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 13.0210,
      longitude: 74.7950
    },
    {
      id: "DK-LA-022",
      name: "Someshwar Eco-Tourism Access Road",
      taluk: "Mangaluru",
      village: "Someshwar",
      projectType: "Tourism Access Road",
      landAreaAcres: 7.8,
      affectedFamilies: 6,
      compensationProgressPct: 92,
      rehabilitationProgressPct: 86,
      documentationProgressPct: 95,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 12,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.7890,
      longitude: 74.8610
    },

    // --- BANTWAL TALUK (8 Projects: 2 High, 4 Med, 2 Low) ---
    {
      id: "DK-LA-002",
      name: "Bantwal Regional Connectivity Project",
      taluk: "Bantwal",
      village: "B.C. Road",
      projectType: "Highway & Bypass Expansion",
      landAreaAcres: 28.0,
      affectedFamilies: 42,
      compensationProgressPct: 76,
      rehabilitationProgressPct: 65,
      documentationProgressPct: 84,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 24,
      delayProbabilityPct: 45,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8790,
      longitude: 75.0320
    },
    {
      id: "DK-LA-009",
      name: "Bantwal Industrial Estate Phase 2",
      taluk: "Bantwal",
      village: "Mani",
      projectType: "Industrial Estate",
      landAreaAcres: 38.0,
      affectedFamilies: 35,
      compensationProgressPct: 62,
      rehabilitationProgressPct: 50,
      documentationProgressPct: 70,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 24,
      delayProbabilityPct: 56,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8390,
      longitude: 75.1050
    },
    {
      id: "DK-LA-023",
      name: "Kalladka Flyover Feeder Corridor",
      taluk: "Bantwal",
      village: "Kalladka",
      projectType: "Flyover Feeder",
      landAreaAcres: 15.4,
      affectedFamilies: 48,
      compensationProgressPct: 38,
      rehabilitationProgressPct: 25,
      documentationProgressPct: 48,
      legalDisputes: 6,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 30,
      delayProbabilityPct: 81,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.8610,
      longitude: 75.0680
    },
    {
      id: "DK-LA-024",
      name: "Vittal Water Treatment Plant Corridor",
      taluk: "Bantwal",
      village: "Vittal",
      projectType: "Water Infrastructure",
      landAreaAcres: 12.0,
      affectedFamilies: 32,
      compensationProgressPct: 44,
      rehabilitationProgressPct: 30,
      documentationProgressPct: 52,
      legalDisputes: 4,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 73,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.7680,
      longitude: 75.1020
    },
    {
      id: "DK-LA-025",
      name: "Farangipete Riverbank Protection Works",
      taluk: "Bantwal",
      village: "Farangipete",
      projectType: "River Protection",
      landAreaAcres: 9.6,
      affectedFamilies: 20,
      compensationProgressPct: 66,
      rehabilitationProgressPct: 58,
      documentationProgressPct: 74,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 49,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8680,
      longitude: 74.9650
    },
    {
      id: "DK-LA-026",
      name: "Melkar Agricultural Produce Market Layout",
      taluk: "Bantwal",
      village: "Melkar",
      projectType: "APMC Market Yard",
      landAreaAcres: 18.0,
      affectedFamilies: 22,
      compensationProgressPct: 60,
      rehabilitationProgressPct: 52,
      documentationProgressPct: 68,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 20,
      delayProbabilityPct: 54,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8600,
      longitude: 75.0120
    },
    {
      id: "DK-LA-027",
      name: "Modankap Educational Complex Expansion",
      taluk: "Bantwal",
      village: "Modankap",
      projectType: "Institutional Infrastructure",
      landAreaAcres: 6.5,
      affectedFamilies: 5,
      compensationProgressPct: 86,
      rehabilitationProgressPct: 80,
      documentationProgressPct: 90,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 20,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.8850,
      longitude: 75.0410
    },
    {
      id: "DK-LA-028",
      name: "Benjanapadavu Skill Development Layout",
      taluk: "Bantwal",
      village: "Benjanapadavu",
      projectType: "Training Complex",
      landAreaAcres: 8.4,
      affectedFamilies: 7,
      compensationProgressPct: 88,
      rehabilitationProgressPct: 82,
      documentationProgressPct: 92,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 14,
      delayProbabilityPct: 18,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.9020,
      longitude: 74.9890
    },

    // --- BELTHANGADY TALUK (6 Projects: 1 High, 2 Med, 3 Low) ---
    {
      id: "DK-LA-005",
      name: "Belthangady Rural Infrastructure Improvement",
      taluk: "Belthangady",
      village: "Ujire",
      projectType: "Rural Road & Bridge Expansion",
      landAreaAcres: 12.4,
      affectedFamilies: 14,
      compensationProgressPct: 88,
      rehabilitationProgressPct: 80,
      documentationProgressPct: 90,
      legalDisputes: 1,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 18,
      delayProbabilityPct: 22,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 13.0150,
      longitude: 75.3280
    },
    {
      id: "DK-LA-029",
      name: "Dharmasthala Pilgrim Corridor & Parking",
      taluk: "Belthangady",
      village: "Dharmasthala",
      projectType: "Pilgrim Corridor",
      landAreaAcres: 21.0,
      affectedFamilies: 38,
      compensationProgressPct: 46,
      rehabilitationProgressPct: 35,
      documentationProgressPct: 58,
      legalDisputes: 5,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 75,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.9510,
      longitude: 75.3780
    },
    {
      id: "DK-LA-030",
      name: "Guruvayanakere Bypass Corridor",
      taluk: "Belthangady",
      village: "Guruvayanakere",
      projectType: "Bypass Road",
      landAreaAcres: 14.5,
      affectedFamilies: 22,
      compensationProgressPct: 68,
      rehabilitationProgressPct: 56,
      documentationProgressPct: 72,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 48,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 13.0020,
      longitude: 75.2950
    },
    {
      id: "DK-LA-031",
      name: "Madanthyar Rural Agro Hub",
      taluk: "Belthangady",
      village: "Madanthyar",
      projectType: "Agro Processing Zone",
      landAreaAcres: 16.0,
      affectedFamilies: 19,
      compensationProgressPct: 65,
      rehabilitationProgressPct: 55,
      documentationProgressPct: 70,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 20,
      delayProbabilityPct: 51,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.9810,
      longitude: 75.1950
    },
    {
      id: "DK-LA-032",
      name: "Laila Civic Amenities Zone",
      taluk: "Belthangady",
      village: "Laila",
      projectType: "Civic Layout",
      landAreaAcres: 7.2,
      affectedFamilies: 6,
      compensationProgressPct: 90,
      rehabilitationProgressPct: 84,
      documentationProgressPct: 94,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 16,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 13.0280,
      longitude: 75.3120
    },
    {
      id: "DK-LA-033",
      name: "Kokkada Sub-Hospital Expansion",
      taluk: "Belthangady",
      village: "Kokkada",
      projectType: "Healthcare Infrastructure",
      landAreaAcres: 5.5,
      affectedFamilies: 4,
      compensationProgressPct: 92,
      rehabilitationProgressPct: 88,
      documentationProgressPct: 95,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 14,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.8850,
      longitude: 75.3850
    },

    // --- PUTTUR TALUK (7 Projects: 2 High, 3 Med, 2 Low) ---
    {
      id: "DK-LA-003",
      name: "Puttur Water Infrastructure & Pipeline Corridor",
      taluk: "Puttur",
      village: "Kabila",
      projectType: "Water & Sanitation Infrastructure",
      landAreaAcres: 16.2,
      affectedFamilies: 28,
      compensationProgressPct: 35,
      rehabilitationProgressPct: 25,
      documentationProgressPct: 55,
      legalDisputes: 5,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 18,
      delayProbabilityPct: 78,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.7660,
      longitude: 75.2010
    },
    {
      id: "DK-LA-010",
      name: "Puttur Railway Overbridge & Feeder Road",
      taluk: "Puttur",
      village: "Darbe",
      projectType: "Rail Infrastructure",
      landAreaAcres: 9.8,
      affectedFamilies: 24,
      compensationProgressPct: 70,
      rehabilitationProgressPct: 60,
      documentationProgressPct: 78,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 48,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.7520,
      longitude: 75.2150
    },
    {
      id: "DK-LA-034",
      name: "Narimogaru Agricultural Processing Zone",
      taluk: "Puttur",
      village: "Narimogaru",
      projectType: "Agro Park",
      landAreaAcres: 26.0,
      affectedFamilies: 42,
      compensationProgressPct: 40,
      rehabilitationProgressPct: 28,
      documentationProgressPct: 50,
      legalDisputes: 6,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 30,
      delayProbabilityPct: 80,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.7210,
      longitude: 75.2420
    },
    {
      id: "DK-LA-035",
      name: "Parladka Commercial Bypass Link",
      taluk: "Puttur",
      village: "Parladka",
      projectType: "Commercial Bypass",
      landAreaAcres: 11.5,
      affectedFamilies: 18,
      compensationProgressPct: 64,
      rehabilitationProgressPct: 52,
      documentationProgressPct: 70,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 53,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.7610,
      longitude: 75.2080
    },
    {
      id: "DK-LA-036",
      name: "Uppinangady River Confluence Bridge",
      taluk: "Puttur",
      village: "Uppinangady",
      projectType: "River Bridge & Feeder",
      landAreaAcres: 14.8,
      affectedFamilies: 25,
      compensationProgressPct: 62,
      rehabilitationProgressPct: 50,
      documentationProgressPct: 68,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 20,
      delayProbabilityPct: 57,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.8390,
      longitude: 75.2510
    },
    {
      id: "DK-LA-037",
      name: "Bellare Sub-Divisional Storage Yard",
      taluk: "Puttur",
      village: "Bellare",
      projectType: "Storage Depot",
      landAreaAcres: 8.0,
      affectedFamilies: 6,
      compensationProgressPct: 88,
      rehabilitationProgressPct: 82,
      documentationProgressPct: 90,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 18,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.6510,
      longitude: 75.3210
    },
    {
      id: "DK-LA-038",
      name: "Kabaka Industrial Sub-Yard",
      taluk: "Puttur",
      village: "Kabaka",
      projectType: "Industrial Layout",
      landAreaAcres: 10.2,
      affectedFamilies: 8,
      compensationProgressPct: 85,
      rehabilitationProgressPct: 78,
      documentationProgressPct: 88,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 14,
      delayProbabilityPct: 22,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.7820,
      longitude: 75.1850
    },

    // --- SULLIA TALUK (4 Projects: 1 High, 2 Med, 1 Low) ---
    {
      id: "DK-LA-006",
      name: "Sullia Forest Fringe Corridor Expansion",
      taluk: "Sullia",
      village: "Jaini",
      projectType: "Eco-Road Corridor",
      landAreaAcres: 34.0,
      affectedFamilies: 22,
      compensationProgressPct: 52,
      rehabilitationProgressPct: 40,
      documentationProgressPct: 60,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 30,
      delayProbabilityPct: 64,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.5620,
      longitude: 75.3900
    },
    {
      id: "DK-LA-039",
      name: "Aranthodu Ghat Road Safety Bypass",
      taluk: "Sullia",
      village: "Aranthodu",
      projectType: "Ghat Road Bypass",
      landAreaAcres: 18.5,
      affectedFamilies: 35,
      compensationProgressPct: 42,
      rehabilitationProgressPct: 30,
      documentationProgressPct: 52,
      legalDisputes: 5,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 77,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.5210,
      longitude: 75.4350
    },
    {
      id: "DK-LA-040",
      name: "Sampaje Border Checkpoint Expansion",
      taluk: "Sullia",
      village: "Sampaje",
      projectType: "Inter-State Checkpoint",
      landAreaAcres: 12.0,
      affectedFamilies: 14,
      compensationProgressPct: 66,
      rehabilitationProgressPct: 55,
      documentationProgressPct: 72,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 52,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.5020,
      longitude: 75.5120
    },
    {
      id: "DK-LA-041",
      name: "Jalthoor Rural Hydro Electric Substation",
      taluk: "Sullia",
      village: "Jalthoor",
      projectType: "Power Substation",
      landAreaAcres: 9.0,
      affectedFamilies: 6,
      compensationProgressPct: 88,
      rehabilitationProgressPct: 82,
      documentationProgressPct: 92,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 19,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.5850,
      longitude: 75.3610
    },

    // --- KADABA TALUK (4 Projects: 1 High, 1 Med, 2 Low) ---
    {
      id: "DK-LA-007",
      name: "Kadaba Sub-Divisional Complex Land",
      taluk: "Kadaba",
      village: "Nelyadi",
      projectType: "Administrative Complex",
      landAreaAcres: 8.5,
      affectedFamilies: 6,
      compensationProgressPct: 82,
      rehabilitationProgressPct: 75,
      documentationProgressPct: 88,
      legalDisputes: 1,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 28,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.7830,
      longitude: 75.3120
    },
    {
      id: "DK-LA-042",
      name: "Ramakunja Railway Feeder Corridor",
      taluk: "Kadaba",
      village: "Ramakunja",
      projectType: "Rail Feeder Road",
      landAreaAcres: 17.5,
      affectedFamilies: 32,
      compensationProgressPct: 43,
      rehabilitationProgressPct: 28,
      documentationProgressPct: 54,
      legalDisputes: 5,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 76,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 12.7450,
      longitude: 75.2850
    },
    {
      id: "DK-LA-043",
      name: "Alankaru Dairy Processing Complex",
      taluk: "Kadaba",
      village: "Alankaru",
      projectType: "Agro Processing Zone",
      landAreaAcres: 14.0,
      affectedFamilies: 18,
      compensationProgressPct: 65,
      rehabilitationProgressPct: 55,
      documentationProgressPct: 70,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 51,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 12.7980,
      longitude: 75.2610
    },
    {
      id: "DK-LA-044",
      name: "Ichlampady River Bridge Layout",
      taluk: "Kadaba",
      village: "Ichlampady",
      projectType: "River Bridge",
      landAreaAcres: 6.8,
      affectedFamilies: 5,
      compensationProgressPct: 90,
      rehabilitationProgressPct: 85,
      documentationProgressPct: 94,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 15,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 12.8120,
      longitude: 75.3450
    },

    // --- MOODBIDRI TALUK (5 Projects: 1 High, 3 Med, 1 Low) ---
    {
      id: "DK-LA-004",
      name: "Moodbidri Industrial Access Corridor",
      taluk: "Moodbidri",
      village: "Mijar",
      projectType: "Industrial Park Infrastructure",
      landAreaAcres: 55.0,
      affectedFamilies: 18,
      compensationProgressPct: 92,
      rehabilitationProgressPct: 88,
      documentationProgressPct: 95,
      legalDisputes: 0,
      approvalStatus: "Approved",
      possessionStatus: "Completed",
      stakeholderResponsiveness: "High",
      projectDurationMonths: 12,
      delayProbabilityPct: 14,
      riskLevel: "LOW",
      status: "On Schedule",
      latitude: 13.0680,
      longitude: 74.9950
    },
    {
      id: "DK-LA-045",
      name: "Alangar Heritage Tourist Ring Road",
      taluk: "Moodbidri",
      village: "Alangar",
      projectType: "Heritage Tourism Ring Road",
      landAreaAcres: 19.5,
      affectedFamilies: 42,
      compensationProgressPct: 39,
      rehabilitationProgressPct: 26,
      documentationProgressPct: 48,
      legalDisputes: 6,
      approvalStatus: "Approved",
      possessionStatus: "Pending",
      stakeholderResponsiveness: "Low",
      projectDurationMonths: 24,
      delayProbabilityPct: 79,
      riskLevel: "HIGH",
      status: "Active Monitoring",
      latitude: 13.0780,
      longitude: 74.9820
    },
    {
      id: "DK-LA-046",
      name: "Gantikette Bio-Tech Industrial Park",
      taluk: "Moodbidri",
      village: "Gantikette",
      projectType: "Industrial Estate",
      landAreaAcres: 24.0,
      affectedFamilies: 26,
      compensationProgressPct: 62,
      rehabilitationProgressPct: 52,
      documentationProgressPct: 68,
      legalDisputes: 3,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 20,
      delayProbabilityPct: 55,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 13.0510,
      longitude: 75.0210
    },
    {
      id: "DK-LA-047",
      name: "Tenkabail Water Reservoir Corridor",
      taluk: "Moodbidri",
      village: "Tenkabail",
      projectType: "Water Infrastructure",
      landAreaAcres: 15.0,
      affectedFamilies: 20,
      compensationProgressPct: 66,
      rehabilitationProgressPct: 56,
      documentationProgressPct: 72,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 48,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 13.0920,
      longitude: 74.9610
    },
    {
      id: "DK-LA-048",
      name: "Mastikatte Civic Infrastructure Layout",
      taluk: "Moodbidri",
      village: "Mastikatte",
      projectType: "Civic Infrastructure",
      landAreaAcres: 11.0,
      affectedFamilies: 14,
      compensationProgressPct: 64,
      rehabilitationProgressPct: 54,
      documentationProgressPct: 70,
      legalDisputes: 2,
      approvalStatus: "Approved",
      possessionStatus: "In Progress",
      stakeholderResponsiveness: "Medium",
      projectDurationMonths: 18,
      delayProbabilityPct: 50,
      riskLevel: "MEDIUM",
      status: "Active Monitoring",
      latitude: 13.0610,
      longitude: 75.0110
    }
  ],

  // Proactive Alerts & Early Warnings
  alerts: [
    {
      id: "ALT-801",
      severity: "CRITICAL",
      projectID: "DK-LA-008",
      projectName: "Mangaluru Smart Logistics Hub",
      message: "Predicted delay probability breached 85% threshold due to 11 active litigation stays.",
      timestamp: "12 mins ago",
      status: "Unread"
    },
    {
      id: "ALT-802",
      severity: "HIGH",
      projectID: "DK-LA-001",
      projectName: "Mangaluru Coastal Infrastructure Expansion",
      message: "Compensation progress stuck at 48% for 45 consecutive days. Milestone overdue.",
      timestamp: "35 mins ago",
      status: "Unread"
    },
    {
      id: "ALT-803",
      severity: "HIGH",
      projectID: "DK-LA-003",
      projectName: "Puttur Water Infrastructure Corridor",
      message: "New land valuation objection filed in Sub-Court by 14 landholders.",
      timestamp: "1 hour ago",
      status: "Unread"
    },
    {
      id: "ALT-804",
      severity: "HIGH",
      projectID: "DK-LA-023",
      projectName: "Kalladka Flyover Feeder Corridor",
      message: "Compensation disbursal below 40% threshold with 6 active land suits.",
      timestamp: "2 hours ago",
      status: "Unread"
    },
    {
      id: "ALT-805",
      severity: "MEDIUM",
      projectID: "DK-LA-006",
      projectName: "Sullia Forest Fringe Corridor Expansion",
      message: "Forest clearance certificate documentation pending approval for over 60 days.",
      timestamp: "3 hours ago",
      status: "Read"
    }
  ],

  // System Notifications
  notifications: [
    { id: 1, text: "AI Risk Prediction Engine updated model weights for Dakshina Kannada.", time: "10 mins ago" },
    { id: 2, text: "Monthly Land Acquisition Report (Sep 2026) ready for download.", time: "1 hour ago" },
    { id: 3, text: "User 'officer@landguard.ai' updated progress on DK-LA-004.", time: "4 hours ago" }
  ]
};

// Make accessible globally
window.LANDGUARD_MOCK_DATA = LANDGUARD_MOCK_DATA;
